// Generated by CoffeeScript 1.3.3
(function() {
  var displayCurrentWeek, row_nums;

  $(document).ready(function() {
    window.week_idx = window.weeks.length - 1;
    displayCurrentWeek();
    $('.ttip').tooltip({
      'html': true
    });
    $('.popper').popover();
    return $('.checkbox').click(function() {
      var day, value;
      $(this).toggleClass('checked');
      value = 1;
      day = "05092013";
      if ($(this).html() === '') {
        $(this).html('•');
      } else {
        $(this).html('');
      }
      return $.post('/update_virtue/' + day + "/", {
        virtue: 'silence',
        value: value
      }, function(data) {
        return console.log(data);
      });
    });
  });

  row_nums = {
    'temperance': 1,
    'silence': 2,
    'order': 3,
    'resolution': 4,
    'frugality': 5,
    'industry': 6,
    'sincerity': 7,
    'justice': 8,
    'moderation': 9,
    'cleanliness': 10,
    'tranquility': 11,
    'chastity': 12,
    'humility': 13
  };

  displayCurrentWeek = function() {
    var current_week, day, day_idx, status, virtue, _i, _len, _ref, _results;
    current_week = weeks[week_idx];
    $('.checkbox').removeClass('checked').html('');
    console.log(current_week);
    _ref = current_week['days'];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      day = _ref[_i];
      _results.push((function() {
        var _results1;
        _results1 = [];
        for (virtue in day) {
          status = day[virtue];
          if (virtue === 'date') {
            continue;
          }
          if (status === 1) {
            day_idx = new Date(day['date'] + " 12:00").getDay() + 2;
            console.log(day_idx, row_nums[virtue]);
            _results1.push($("table tr:nth-child(" + row_nums[virtue] + ") td:nth-child(" + day_idx + ")").addClass('checked').html('•'));
          } else {
            _results1.push(void 0);
          }
        }
        return _results1;
      })());
    }
    return _results;
  };

}).call(this);
