// Generated by CoffeeScript 1.6.3
(function() {
  $('.ttip').tooltip({
    'html': true
  });

  $('.popper').popover();

  $('.checkbox').click(function() {
    $(this).addClass('checked');
    return $(this).html('•');
  });

}).call(this);
