// Generated by CoffeeScript 1.3.3
(function() {
  var displayCurrentWeek, row_nums;

  $(document).ready(function() {
    var nextWeek, prevWeek, touchHandler;
    touchHandler = function(event) {
      var first, simulatedEvent, touches, type;
      touches = event.changedTouches;
      first = touches[0];
      type = "";
      switch (event.type) {
        case "touchstart":
          type = "mousedown";
          break;
        case "touchmove":
          type = "mousemove";
          break;
        case "touchend":
          type = "mouseup";
          break;
        default:
          return;
      }
      simulatedEvent = document.createEvent("MouseEvent");
      simulatedEvent.initMouseEvent(type, true, true, window, 1, first.screenX, first.screenY, first.clientX, first.clientY, false, false, false, false, 0, null);
      return first.target.dispatchEvent(simulatedEvent);
    };
    document.addEventListener("touchstart", touchHandler, true);
    document.addEventListener("touchmove", touchHandler, true);
    document.addEventListener("touchend", touchHandler, true);
    document.addEventListener("touchcancel", touchHandler, true);
    window.week_idx = window.weeks.length - 1;
    displayCurrentWeek();
    $('.ttip').tooltip({
      'html': true
    });
    $('.popper').popover({
      trigger: 'hover'
    });
    $('.checkbox').click(function() {
      var current_week, day, value, virtue, week_start_date;
      $(this).toggleClass('checked');
      virtue = $(this).data('virtue').toLowerCase();
      value = 1;
      current_week = weeks[week_idx];
      week_start_date = new Date(current_week['start_date'] + " 12:00");
      week_start_date.setDate(week_start_date.getDate() + $(this).data('weekday'));
      day = padDigits(week_start_date.getDate(), 2) + padDigits(week_start_date.getMonth() + 1, 2) + week_start_date.getFullYear();
      if ($(this).html() === '') {
        $(this).html('•');
      } else {
        $(this).html('');
        value = 0;
      }
      return $.post('/update_virtue/' + day + "/", {
        virtue: virtue,
        value: value
      }, function(data) {
        return console.log(data);
      });
    });
    prevWeek = function() {
      if (window.week_idx <= 0) {
        return;
      }
      console.log("HELLO", window.week_idx);
      window.week_idx = window.week_idx - 1;
      displayCurrentWeek();
      return false;
    };
    nextWeek = function() {
      if (window.week_idx >= weeks.length - 1) {
        return;
      }
      window.week_idx = window.week_idx + 1;
      displayCurrentWeek();
      return false;
    };
    $('.next_btn').click(nextWeek);
    return $('.prev_btn').click(prevWeek);
  });

  row_nums = {
    'temperance': 1,
    'silence': 2,
    'order': 3,
    'resolution': 4,
    'frugality': 5,
    'industry': 6,
    'sincerity': 7,
    'justice': 8,
    'moderation': 9,
    'cleanliness': 10,
    'tranquility': 11,
    'chastity': 12,
    'humility': 13
  };

  displayCurrentWeek = function() {
    var current_week, day, day_idx, status, virtue, _i, _len, _ref;
    current_week = weeks[week_idx];
    $('.checkbox').removeClass('checked').html('');
    console.log(current_week);
    _ref = current_week['days'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      day = _ref[_i];
      for (virtue in day) {
        status = day[virtue];
        if (virtue === 'date') {
          continue;
        }
        if (status === 1) {
          day_idx = new Date(day['date'] + " 12:00").getDay() + 2;
          console.log(day_idx, row_nums[virtue]);
          $("table tr:nth-child(" + row_nums[virtue] + ") td:nth-child(" + day_idx + ") a").addClass('checked').html('•');
        }
      }
    }
    $('.prev_btn').show();
    $('.next_btn').show();
    if (week_idx === 0) {
      $('.prev_btn').hide();
    }
    if (week_idx === weeks.length - 1) {
      return $('.next_btn').hide();
    }
  };

  window.padDigits = function(number, digits) {
    return Array(Math.max(digits - String(number).length + 1, 0)).join(0) + number;
  };

}).call(this);
